# docker-compose.yml for gRPC generators

# to build the images:  docker-compose build
# to build start everything: docker-compose up --build
# to build start everything after code change: docker-compose up --build

version: '3.9'

services:
    protocomp:
      #build:
      #  context: .
      image: ghcr.io/LARAsuite/grpc-web-generators/grpc_generators:develop
      #restart: unless-stopped
      volumes:
        - ./protos:/protos
        - ./generated:/generated
      #ports:
      #environment:
      #env_file:
      #  - ./.env.dev
      command: 
        - /bin/bash
        #sh -c ""

    
volumes:
  protos:
  generated:

 

